package ru.dmitrykuzmin.eroom.common.model.enums;

/**
 * Created by DmitryComp on 04.09.2014.
 */
public enum DistrictType {
    AVTOVOKZAL, ACADEMICHESKY, BOTANICHESKY,
    VIZ, VOKZALNIY, VTUZGORODOCK, GORNIYSHIT,
    ELIZAVET, JBI, JELEZNODOROJNIY, ZAVOKZALNIY,
    ZARECHNIY, IZOPLIT, ISTOK, KALINOVSKIY, KOLTSOVO,
    KOMPRESSORNIY, KRASNOLESIE, LECHEBNIY, MEDNIY,
    NEW_SORTIROVKA, NIZNEISETSKY, PALNIKS, PARKOVIY,
    PIONERSKY, PTIZEFABRICA, OLD_SORTIROVKA, SADOVIY,
    SEM_KLUCHEY, SIBIRSKY, SINIE_KAMNY, SOVHOZ, UNZ,
    UKTUS, URALMASH, HIMMASH, CENTER,
    VTORCHERMET,
    CHKALOVSKY,
    CHUSOVSKOE_OZERO, SHARTASH, SHARTASHSKIY_RINOK, SHINNIY,
    SHIROKAA_RECHKA, CHUVAKISH, ELMASH, UGO_ZAPADNIY, YUZNIY
}
